id = "scss"
name = "SCSS"
description = "SCSS support"
version = "0.1.1"
schema_version = 1
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
repository = "https://github.com/bajrangCoder/zed-scss"

[grammars.scss]
repository = "https://github.com/savetheclocktower/tree-sitter-scss"
commit = "f5dfc3b4609d01fb11af8c97f3948fffeff25e92"

[language_servers.scss-lsp]
name = "SCSS Language Server"
language = "SCSS"

[language_servers.some-sass-lsp]
name = "Some Sass Language Server"
language = "SCSS"
