id = "scss"
name = "SCSS"
description = "SCSS and SASS support"
version = "0.1.4"
schema_version = 1
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
repository = "https://github.com/bajrangCoder/zed-scss"

[grammars.scss]
repository = "https://github.com/savetheclocktower/tree-sitter-scss"
rev = "f5dfc3b4609d01fb11af8c97f3948fffeff25e92"


[grammars.sass]
repository = "https://github.com/bajrangCoder/tree-sitter-sass"
rev = "26e67021380a2fe0cda89bafd2e131d554f3d2af"

[language_servers.scss-lsp]
name = "SCSS Language Server"
languages = ["SCSS"]

[language_servers.some-sass-lsp]
name = "Some Sass Language Server"
languages = ["SCSS", "SASS"]

[language_servers.some-sass-lsp.language_ids]
"SCSS" = "scss"
"SASS" = "sass"
