name = "SASS"
grammar = "sass"
path_suffixes = ["sass"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
autoclose_before = ":.,=}])>"
brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "#{", end = "}", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
]
word_characters = ["-", "$"]
completion_query_characters = ["-"]
prettier_parser_name = "sass"
